# Generated by Django 4.2.23 on 2025-08-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poll_name", models.CharField(max_length=124)),
                ("question", models.TextField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiring_date", models.DateField(help_text="Date when poll expires")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=32)),
                ("password_hash", models.CharField(max_length=256)),
                (
                    "role",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("ADMIN", "Admin")],
                        default="CLIENT",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField(max_length=1024)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_options",
                        to="polling_app.poll",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="poll",
            name="creater_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="polling_app.user",
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("casted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polling_app.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polling_app.user",
                    ),
                ),
                (
                    "vote_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polling_app.voteoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "db_table": "votes",
                "ordering": ["-casted_at"],
                "unique_together": {("user", "poll")},
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="polling_app.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="polling_app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Registration",
                "verbose_name_plural": "Poll Registrations",
                "db_table": "poll_registrations",
                "unique_together": {("user", "poll")},
            },
        ),
    ]
