# Generated by Django 4.2.23 on 2025-08-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polling_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteoption",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_options",
                to="polling_app.poll",
            ),
        ),
    ]
